from typing import AsyncGenerator, Protocol


class LLMProvider(Protocol):
    name: str
    async def complete(self, messages: list[dict], temperature: float, max_tokens: int) -> str: ...
    async def structured(self, messages: list[dict], schema: dict, temperature: float, max_tokens: int) -> dict: ...
    def stream(self, messages: list[dict], temperature: float, max_tokens: int) -> AsyncGenerator[str, None]: ...
    async def close(self) -> None: ...
